apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: forgescan-base

namespace: forgescan

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/version: "0.1.0"
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - api-deployment.yaml
  - scanner-deployment.yaml
  - database.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: forgescan-platform

images:
  - name: ghcr.io/forge-cyber/forgescan-api
    newTag: latest
  - name: ghcr.io/forge-cyber/forgescan-scanner
    newTag: latest
