---
apiVersion: v1
kind: Namespace
metadata:
  name: forgescan
  labels:
    app.kubernetes.io/name: forgescan
    app.kubernetes.io/part-of: forgescan-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgescan-scanners
  labels:
    app.kubernetes.io/name: forgescan-scanners
    app.kubernetes.io/part-of: forgescan-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgescan-data
  labels:
    app.kubernetes.io/name: forgescan-data
    app.kubernetes.io/part-of: forgescan-platform
